Repository SSUMC-8th/Spring_Boot_A, pull requests merged in 2025-05, with the labels that each got.

#23 [리무] Chapter 6. JPA 활용
  .gitignore
  build.gradle
  src/main/generated/umc/spring/domain/QFood.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QTerms.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/StudyApplication.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/domain/Terms.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/StoreRespository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRespository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRespository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#22 [우디] Chapter 6. JPA 활용
  src/main/generated/umc/spring/domain/QFavoredFood.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewComment.java
  src/main/generated/umc/spring/domain/QReviewImage.java
  src/main/generated/umc/spring/domain/QStore.java
  src/main/generated/umc/spring/domain/QStoreImage.java
  src/main/generated/umc/spring/domain/QStoreOpenHours.java
  src/main/generated/umc/spring/domain/QTerm.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QMemberAgree.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/FavoredFood.java
  src/main/java/umc/spring/domain/Region.java
  src/main/java/umc/spring/domain/Store.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryService.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
Labels: ✨ Chapter06

#24 [이안] Chapter 6. JPA 활용
  build.gradle
  src/main/generated/umc/spring/domain/QFoodCategory.java
  src/main/generated/umc/spring/domain/QMarket.java
  src/main/generated/umc/spring/domain/QMember.java
  src/main/generated/umc/spring/domain/QMission.java
  src/main/generated/umc/spring/domain/QMissionNotification.java
  src/main/generated/umc/spring/domain/QNotification.java
  src/main/generated/umc/spring/domain/QOpenTime.java
  src/main/generated/umc/spring/domain/QRegion.java
  src/main/generated/umc/spring/domain/QReview.java
  src/main/generated/umc/spring/domain/QReviewImage.java
  src/main/generated/umc/spring/domain/QReviewNotification.java
  src/main/generated/umc/spring/domain/QTerm.java
  src/main/generated/umc/spring/domain/common/QBaseEntity.java
  src/main/generated/umc/spring/domain/mapping/QAgreement.java
  src/main/generated/umc/spring/domain/mapping/QMemberMission.java
  src/main/generated/umc/spring/domain/mapping/QMemberPrefer.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/config/QueryDSLConfig.java
  src/main/java/umc/spring/domain/Market.java
  src/main/java/umc/spring/domain/Mission.java
  src/main/java/umc/spring/domain/Notification.java
  src/main/java/umc/spring/domain/OpenTime.java
  src/main/java/umc/spring/domain/Review.java
  src/main/java/umc/spring/domain/Term.java
  src/main/java/umc/spring/repository/MarketRepository.java
  src/main/java/umc/spring/repository/MarketRepositoryCustom.java
  src/main/java/umc/spring/repository/MarketRepositoryImpl.java
  src/main/java/umc/spring/service/MarketQueryService.java
  src/main/java/umc/spring/service/MarketQueryServiceImpl.java
Labels: ✨ Chapter06

#31 [주니] Chapter 7. API 응답 통일 & 에러 핸들러
  .gitignore
  .idea/misc.xml
  .idea/modules.xml
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/repository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepositoryCustom.java
  src/main/java/umc/spring/repository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
  src/main/resources/application.yml
Labels: ✨ Chapter07

#30 [리무] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handle/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/domain/Member.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#33 [우디] Chapter 7. API 응답 통일 & 에러 핸들러
  src/main/java/umc/spring/apiPayLoad/ApiResponse.java
  src/main/java/umc/spring/apiPayLoad/code/BaseCode.java
  src/main/java/umc/spring/apiPayLoad/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayLoad/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayLoad/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayLoad/code/status/SuccessStatus.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/exception/ExceptionAdvice.java
  src/main/java/umc/spring/exception/GeneralException.java
  src/main/java/umc/spring/exception/handler/TempHandler.java
  src/main/java/umc/spring/service/TempService/TempCommandService.java
  src/main/java/umc/spring/service/TempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/TempService/TempQueryService.java
  src/main/java/umc/spring/service/TempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempResponse.java
  src/main/resources/application.yml
Labels: ✨ Chapter07

#28 [이안] Chapter 7. API 응답 통일 & 에러 핸들러
  build.gradle
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/ApiResponse.java
  src/main/java/umc/spring/apiPayload/code/BaseCode.java
  src/main/java/umc/spring/apiPayload/code/BaseErrorCode.java
  src/main/java/umc/spring/apiPayload/code/ErrorReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/ReasonDTO.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/code/status/SuccessStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/apiPayload/exception/GeneralException.java
  src/main/java/umc/spring/apiPayload/exception/handler/TempHandler.java
  src/main/java/umc/spring/converter/TempConverter.java
  src/main/java/umc/spring/service/tempService/TempCommandService.java
  src/main/java/umc/spring/service/tempService/TempCommandServiceImpl.java
  src/main/java/umc/spring/service/tempService/TempQueryService.java
  src/main/java/umc/spring/service/tempService/TempQueryServiceImpl.java
  src/main/java/umc/spring/web/controller/TempRestController.java
  src/main/java/umc/spring/web/dto/TempRequest.java
  src/main/java/umc/spring/web/dto/TempResponse.java
Labels: ✨ Chapter07

#37 [이안] Chapter 8. API & Swagger & Annotation
  build.gradle
  src/main/generated/umc/spring/domain/QMarket.java
  src/main/java/umc/spring/Application.java
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/BadRequestException.java
  src/main/java/umc/spring/apiPayload/exception/NotFoundException.java
  src/main/java/umc/spring/config/SwaggerConfig.java
  src/main/java/umc/spring/converter/MarketConverter.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/domain/Market.java
  src/main/java/umc/spring/domain/enums/Progress.java
  src/main/java/umc/spring/domain/mapping/MemberMission.java
  src/main/java/umc/spring/repository/FoodCategoryRepository.java
  src/main/java/umc/spring/repository/MarketRepository.java
  src/main/java/umc/spring/repository/MarketRepositoryCustom.java
  src/main/java/umc/spring/repository/MarketRepositoryImpl.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/repository/RegionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/MarketQueryService.java
  src/main/java/umc/spring/service/MarketQueryServiceImpl.java
  src/main/java/umc/spring/service/marektService/MarketCommandService.java
  src/main/java/umc/spring/service/marektService/MarketCommandServiceImpl.java
  src/main/java/umc/spring/service/marektService/dto/MarketRequestDTO.java
  src/main/java/umc/spring/service/marektService/dto/MarketResponseDTO.java
  src/main/java/umc/spring/service/missionService/MissionCommandService.java
  src/main/java/umc/spring/service/missionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/missionService/dto/MissionRequestDTO.java
  src/main/java/umc/spring/service/missionService/dto/MissionResponseDTO.java
  src/main/java/umc/spring/service/reviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/reviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/service/reviewService/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/service/reviewService/dto/ReviewResponseDTO.java
  src/main/java/umc/spring/validator/ExistingCategoryValidator.java
  src/main/java/umc/spring/validator/annotation/ExistingCategory.java
  src/main/java/umc/spring/web/controller/MarketController.java
  src/main/java/umc/spring/web/controller/MissionController.java
  src/main/java/umc/spring/web/controller/ReviewController.java
Labels: ✨ Chapter08

#39 [주니] Chapter 8. API & Swagger & Annotation
  .idea/modules.xml
  build.gradle
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/handler/MemberHandler.java
  src/main/java/umc/spring/apiPayload/exception/handler/MissionHandler.java
  src/main/java/umc/spring/apiPayload/exception/handler/RegionHandler.java
  src/main/java/umc/spring/apiPayload/exception/handler/StoreHandler.java
  src/main/java/umc/spring/config/SwaggerConfig/SwaggerConfig.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/converter/StoreConverter.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MemberRepository.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/repository/RegionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/repository/StoreRepository.java
  src/main/java/umc/spring/repository/StoreRepositoryImpl.java
  src/main/java/umc/spring/service/MissionService/MissionCommandService.java
  src/main/java/umc/spring/service/MissionService/MissionCommandServiceImpl.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandService.java
  src/main/java/umc/spring/service/ReviewService/ReviewCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreCommandService.java
  src/main/java/umc/spring/service/StoreService/StoreCommandServiceImpl.java
  src/main/java/umc/spring/service/StoreService/StoreQueryServiceImpl.java
  src/main/java/umc/spring/validation/annotation/ChallengedMission.java
  src/main/java/umc/spring/validation/annotation/ExistStores.java
  src/main/java/umc/spring/validation/validator/ChallengedMissionValidaotor.java
  src/main/java/umc/spring/validation/validator/StoresExistValidator.java
  src/main/java/umc/spring/web/controller/MissionRestController.java
  src/main/java/umc/spring/web/controller/ReviewRestController.java
  src/main/java/umc/spring/web/controller/StoreRestController.java
  src/main/java/umc/spring/web/dto/MissionRequestDTO.java
  src/main/java/umc/spring/web/dto/MissionResponseDTO.java
  src/main/java/umc/spring/web/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/web/dto/ReviewResponseDTO.java
  src/main/java/umc/spring/web/dto/StoreRequestDTO.java
  src/main/java/umc/spring/web/dto/StoreResponseDTO.java
Labels: ✨ Chapter08

#48 [이안] Chapter 9. API & Paging
  src/main/java/umc/spring/apiPayload/code/status/ErrorStatus.java
  src/main/java/umc/spring/apiPayload/exception/ExceptionAdvice.java
  src/main/java/umc/spring/config/WebConfig.java
  src/main/java/umc/spring/converter/MemberMissionConverter.java
  src/main/java/umc/spring/converter/MissionConverter.java
  src/main/java/umc/spring/converter/ReviewConverter.java
  src/main/java/umc/spring/repository/MarketRepository.java
  src/main/java/umc/spring/repository/MemberMissionRepository.java
  src/main/java/umc/spring/repository/MissionRepository.java
  src/main/java/umc/spring/repository/ReviewRepository.java
  src/main/java/umc/spring/service/marektService/dto/MarketRequestDTO.java
  src/main/java/umc/spring/service/marektService/dto/MarketResponseDTO.java
  src/main/java/umc/spring/service/membermissionService/MemberMissionQueryService.java
  src/main/java/umc/spring/service/membermissionService/MemberMissionQueryServiceImpl.java
  src/main/java/umc/spring/service/membermissionService/dto/MemberMissionResponseDTO.java
  src/main/java/umc/spring/service/missionService/MissionQueryService.java
  src/main/java/umc/spring/service/missionService/MissionQueryServiceImpl.java
  src/main/java/umc/spring/service/missionService/dto/MissionRequestDTO.java
  src/main/java/umc/spring/service/missionService/dto/MissionResponseDTO.java
  src/main/java/umc/spring/service/reviewService/ReviewQueryService.java
  src/main/java/umc/spring/service/reviewService/ReviewQueryServiceImpl.java
  src/main/java/umc/spring/service/reviewService/dto/ReviewRequestDTO.java
  src/main/java/umc/spring/service/reviewService/dto/ReviewResponseDTO.java
  src/main/java/umc/spring/validation/annotation/ExistMarket.java
  src/main/java/umc/spring/validation/annotation/ExistingCategory.java
  src/main/java/umc/spring/validation/annotation/ValidPage.java
  src/main/java/umc/spring/validation/resolver/ValidPageResolver.java
  src/main/java/umc/spring/validation/validator/ExistingCategoryValidator.java
  src/main/java/umc/spring/validation/validator/MarketExistValidator.java
  src/main/java/umc/spring/web/controller/MemberMissionController.java
  src/main/java/umc/spring/web/controller/MissionController.java
  src/main/java/umc/spring/web/controller/ReviewController.java
Labels: ✨Chapter09
